### PR TITLE
V0.4.3

### PR DESCRIPTION
**Pull request by kellyjosephprice**

### CODE REVIEW

**Comment by kellyjosephprice** [comment]
I'm not sure what's going on, but it will print each example 1-8 times?!

**Comment by aake** [comment]
Shouldn't this be a major version bump since it's not backwards compatible?

**Comment by kellyjosephprice** [comment]
That makes sense, yes.

**Comment by kdole** [comment]
Do you want to update the README for which RSpec versions are supported?

**Pull request merged**
