### PR TITLE
Update exit codes and rescue general errors

### PR DESCRIPTION
**Pull request by kellyjosephprice**

### CODE REVIEW

**Comment by jacobbloomCDD** [comment]
We may want specs for error codes?  Other than that, LGTM

**Comment by kellyjosephprice** [comment]
Err, it looks like I forgot to include any actual specs for exit codes. I think I ran into some environment problems trying to run multirspec. But, yes, I think we should have some.

**Comment by kellyjosephprice** [comment]
I'm not sure that it's worth the time to handle the other 2 exit cases. I can only think of really contrived ways to get them to happen.

**Comment by jacobbloomCDD** [comment]
LGTM

**Pull request merged**
